/**
 * 
 */
package com.bluedotinnovation.application;


import java.io.IOException;
import java.io.InputStream;
import java.util.Date;

import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClientBuilder;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import com.bluedotinnovation.common.BDCommon;


/**
 * @author Bluedot Innovation
 * Add application java client demonstrates adding an application to your Bluedot backend using Apache HTTP client and JSON Simple libraries.
 */
public class AddApplication extends BDCommon
{

    private static String bdRestUrl           = "https://api.bluedotinnovation.com/1/applications";
	/**
	 * @param args
	 * @throws IOException 
	 * @throws ParseException
	 */
	public static void main(String[] args) throws IOException, ParseException
	{
		String bdCustomerApiKey    = "ca4c8d11-6942-11e4-ba4b-a0481cdc3311"; //This key is generated by Bluedot Access UI when you register

		
		CloseableHttpClient httpRestClient  = HttpClientBuilder.create().build();
		
		HttpPost postRequest = new HttpPost(bdRestUrl);
	   //TO DO - Remove creation time and last update time. This should be on the server
		String application = "{ \"security\": {\"customerApiKey\":" +"\"" +bdCustomerApiKey + "\"" +"}," +
		    "\"content\": {\"application\" : {\"name\" : \"Test Application-After-Create\", \"packageName\": \"au.com.bluedot.creationtestbd\"," +
		    "\"nextRuleUpdateInterval\": 1000, \"lastUpdateTime\":"  + "\"" +new Date()+ "\"" + "," +
		    "\"creationTime\":"  + "\"" +new Date()+ "\"" + ",\"status\": \"ACTIVE\",\"enableDataAnonymisation\": \"false\",\"nextRuleUpdateIntervalFormatted\": \"00:05\",\"apiKey\" : \"none\"}}}";
			
		
	    JSONObject bdApplicationJSONObject;	    
	    JSONParser parser       = new JSONParser();
	    bdApplicationJSONObject = (JSONObject)  parser.parse(application);
				    
	   /* Or hand build the json object
	      JSONObject application  = new JSONObject();		     		     
		  JSONObject securityNode = new JSONObject();
		  securityNode.put("customerApiKey", "bc199c80-5441-11e4-b7bb-a0481cdc3311");		    
		  application.put("security", securityNode); 
	   */
		    
		postRequest.addHeader("content-type", "application/json");

		postRequest.setEntity(new StringEntity(bdApplicationJSONObject.toJSONString()));
	 
	    HttpResponse response = httpRestClient.execute(postRequest);
        if (response.getStatusLine().getStatusCode() == 200)
        {
        	System.out.println("Application was successfully created");
        	InputStream inputStream = response.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json result
        	JSONObject jsonResult   = (JSONObject)  parser.parse(resultString);
        	System.out.println("apiKey for your application is : " + jsonResult.get("apiKey"));
        }
        else 
        {
        	InputStream inputStream = response.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json error result
        	System.out.println(resultString);
        }			
	}
		
}
