package com.bluedotinnovation.action;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.Charset;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;

import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import com.bluedotinnovation.common.BDCommon;

/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Add Action with conditions client demonstrates adding an action with different types of conditions to an existing zone 
 * using JSON simple and Apache HTTP client libraries.
 */

public class AddActionWithConditions extends BDCommon {
	
	private static String bdCustomerApiKey    	= "CUSTOMER_API_KEY_HERE"; //This key is generated by Bluedot Point Access UI when your account is created.
	private static String bdApplicationApiKey  	= "APPLICATION_API_KEY_HERE"; //This apiKey is generated when you create an application
	private static String bdZoneId            	= "ZONE_ID_HERE"; //This is the id of the zone being updated. This can be fetched by calling GET Zones API
    private static String bdRestUrl           	= "https://api.bluedotinnovation.com/1/actions";
	
	/**
	 * @param args
	 * @throws IOException 
	 * @throws ParseException
	 * @throws NoSuchAlgorithmException 
	 * @throws KeyManagementException 
	 */
	public static void main(String[] args) throws  IOException, ParseException, KeyManagementException, NoSuchAlgorithmException {
		
		CloseableHttpClient httpRestClient = HttpClients.custom().setSSLSocketFactory(getSSLContextFactory()).build();
		
		HttpPost postRequest = new HttpPost(bdRestUrl);
  
	    JSONParser parser    = new JSONParser();
	    JSONObject bdMessageActionWithCondtionsJSONObject = (JSONObject) parser.parse(getJsonActionWithSequentialCondition()); //action with sequential condition json
				    		    
		postRequest.addHeader("content-type", "application/json");

		postRequest.setEntity(new StringEntity(bdMessageActionWithCondtionsJSONObject.toJSONString(), Charset.defaultCharset()));
	 
	    HttpResponse response = httpRestClient.execute(postRequest);
	    	    	    
        if (response.getStatusLine().getStatusCode() == 200) {
        	System.out.println("Message action and conditions were added to your zone successfully");
        	InputStream inputStream = response.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json result
        	JSONObject jsonResult   = (JSONObject)  parser.parse(resultString);
        	System.out.println(jsonResult);
        } else {
        	InputStream inputStream = response.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json error result
        	System.out.println(resultString);
        }			
	}

    /* Example of Custom Action with Percentage Crossed condition. */
	private static String getJsonActionWithPercentageCrossedCondition() {
		
		String customActionWithPercentageCrossedCondtionJson =
			 "{" +
	            "\"security\": {" +
	                "\"apiKey\":" + "\"" + bdApplicationApiKey +"\"," +
	                "\"customerApiKey\":" +"\"" + bdCustomerApiKey + "\""+
	            "}," +
	            "\"content\": {" +
	                "\"zone\": {" +
	                    "\"zoneId\":"+ "\"" + bdZoneId +"\"," +
	            	    "\"actions\": {" +
	            	    "\"customActions\": [" +
	                        "{" +
	                            "\"name\": \"A Custom Action with Percentage Crossed Condition\"," +
	                            "\"conditions\": {" +
	                               "\"percentageCrossed\": [" +
	                                  "{" +
	                                      "\"percentage\": 90," +
	                                      "\"timeoutPeriod\": \"00:15\"" +
	                                   "}" +
	                              "]" +
	                           "}" +
	                        "}" +
	                    "]" +
	                  "}" +
	                "}" +
	            "}" +
	        "}";
		return customActionWithPercentageCrossedCondtionJson;
	}
	
	/* Example of Custom Action with Sequential condition. */
	private static String getJsonActionWithSequentialCondition() {
		
		String customActionWithSequentialCondtionJson =
			 "{" +
	            "\"security\": {" +
	                "\"apiKey\":" + "\"" + bdApplicationApiKey +"\"," +
	                "\"customerApiKey\":" +"\"" + bdCustomerApiKey + "\""+
	            "}," +
	            "\"content\": {" +
	                "\"zone\": {" +
	                    "\"zoneId\":"+ "\"" + bdZoneId +"\"," +
	            	    "\"actions\": {" +
	            	    "\"customActions\": [" +
	                        "{" +
	                            "\"name\": \"A Custom Action with a Sequential Percentage Crossed Condition\"," +
	                            "\"conditions\": {" +
	                               "\"percentageCrossed\": [" +
	                                  "{" +
	                                      "\"percentage\": 90," +
	                                      "\"timeoutPeriod\": \"00:15\"," +
	                                      "\"sequential\": true" +
	                                   "}" +
	                              "]" +
	                           "}" +
	                        "}" +
	                    "]" +
	                  "}" +
	                "}" +
	            "}" +
	        "}";
		return customActionWithSequentialCondtionJson;
	}
	
	/* Example of Custom Action with Date Range condition. */
	private static String getJsonActionWithDateRangeCondition() {
		
		String customActionWithDateRangeCondtionJson =
			 "{" +
	            "\"security\": {" +
	                "\"apiKey\":" + "\"" + bdApplicationApiKey +"\"," +
	                "\"customerApiKey\":" +"\"" + bdCustomerApiKey + "\""+
	            "}," +
	            "\"content\": {" +
	                "\"zone\": {" +
	                    "\"zoneId\":"+ "\"" + bdZoneId +"\"," +
	            	    "\"actions\": {" +
	            	    "\"customActions\": [" +
	                        "{" +
	                            "\"name\": \"A Custom Action with a Date Condition\"," +
	                            "\"conditions\": {" +
	                            "\"dateRange\": [" +
	                                "{" +
	                                    "\"start\": \"10/11/2016\"," +
	                                    "\"end\": \"26/12/2017\"" +
	                                "}" +
	                            "]" +
	                           "}" +
	                        "}" +
	                    "]" +
	                  "}" +
	                "}" +
	            "}" +
	        "}";
		return customActionWithDateRangeCondtionJson;
	}
	
	/* Example of Custom Action with Time Active condition. */
	private static String getJsonActionWithTimeActiveCondition() {
		
		String customActionWithTimeActiveCondtionJson =
			 "{" +
	            "\"security\": {" +
	                "\"apiKey\":" + "\"" + bdApplicationApiKey +"\"," +
	                "\"customerApiKey\":" +"\"" + bdCustomerApiKey + "\""+
	            "}," +
	            "\"content\": {" +
	                "\"zone\": {" +
	                    "\"zoneId\":"+ "\"" + bdZoneId +"\"," +
	            	    "\"actions\": {" +
	            	    "\"customActions\": [" +
	                        "{" +
	                            "\"name\": \"A Custom Action with a Time Condition\"," +
	                            "\"conditions\": {" +
		                            "\"timeActive\": [{" +
		                                "\"from\": {" +
		                                    "\"time\": \"06:01\"," +
		                                    "\"period\": \"am\" " +
		                                "}," +
		                                "\"to\": {" +
		                                    "\"time\": \"11:00\"," +
		                                    "\"period\": \"pm\" " +
		                                "}" +
		                            "}]" +
	                           "}" +
	                        "}" +
	                    "]" +
	                  "}" +
	                "}" +
	            "}" +
	        "}";
		return customActionWithTimeActiveCondtionJson;
	}
	
	/* Example of Custom Action with Bearing condition. */
	private static String getJsonActionWithBearingCondition() {
		
		String customActionWithBearingCondtionJson =
			 "{" +
	            "\"security\": {" +
	                "\"apiKey\":" + "\"" + bdApplicationApiKey +"\"," +
	                "\"customerApiKey\":" +"\"" + bdCustomerApiKey + "\""+
	            "}," +
	            "\"content\": {" +
	                "\"zone\": {" +
	                    "\"zoneId\":"+ "\"" + bdZoneId +"\"," +
	            	    "\"actions\": {" +
	            	    "\"customActions\": [" +
	                        "{" +
	                            "\"name\": \"A Custom Action with a Time Condition\"," +
	                            "\"conditions\": {" +
	                            "\"bearing\": [" +
	                                "{" +
	                                    "\"fromAngle\": 0," +
	                                    "\"toAngle\": 90" +
	                                "}" +
	                            "]" +
	                           "}" +
	                        "}" +
	                    "]" +
	                  "}" +
	                "}" +
	            "}" +
	        "}";
		return customActionWithBearingCondtionJson;
	}
	
	/* Example of Custom Action with Speed condition. */
	private static String getJsonActionWithSpeedCondition() {
		
		String customActionWithSpeedCondtionJson =
			 "{" +
	            "\"security\": {" +
	                "\"apiKey\":" + "\"" + bdApplicationApiKey +"\"," +
	                "\"customerApiKey\":" +"\"" + bdCustomerApiKey + "\""+
	            "}," +
	            "\"content\": {" +
	                "\"zone\": {" +
	                    "\"zoneId\":"+ "\"" + bdZoneId +"\"," +
	            	    "\"actions\": {" +
	            	    "\"customActions\": [" +
	                        "{" +
	                            "\"name\": \"A Custom Action with a Time Condition\"," +
	                            "\"conditions\": {" +
	                            "\"speed\": [" +
	                                "{" +
	                                    "\"minmumSpeed\": 10," +
	                                    "\"maximumSpeed\": 20" +
	                                "}" +
	                            "]" +
	                           "}" +
	                        "}" +
	                    "]" +
	                  "}" +
	                "}" +
	            "}" +
	        "}";
		return customActionWithSpeedCondtionJson;
	}

}
