package com.bluedotinnovation.action;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.Charset;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;

import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import com.bluedotinnovation.common.BDCommon;

/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation Pty Ltd. All rights reserved.
 * Add Message Action with Conditions client demonstrates adding a message action with all conditions to an existing zone 
 * using JSON simple and Apache HTTP client libraries.
 */

public class AddMessageActionWithConditions extends BDCommon {

	private static String bdCustomerApiKey    	= "CUSTOMER_API_KEY_HERE"; //This key is generated by Bluedot Point Access UI when your account is created.
	private static String bdApplicationApiKey  	= "APPLICATION_API_KEY_HERE"; //This apiKey is generated when you create an application
	private static String bdZoneId            	= "ZONE_ID_HERE"; //This is the id of the zone being updated. This can be fetched by calling GET Zones API
	private static String bdRestUrl           = "https://api.bluedotinnovation.com/1/actions";

	public static void main(String[] args) throws IOException, ParseException, KeyManagementException, NoSuchAlgorithmException {

		CloseableHttpClient httpRestClient = HttpClients.custom().setSSLSocketFactory(getSSLContextFactory()).build();
		
		JSONParser parser    = new JSONParser();
		JSONObject bdMessageActionJSONObject = (JSONObject) parser.parse(getJsonMessageActionWithConditions()); //Message action with conditions json
		
		HttpPost postRequest = new HttpPost(bdRestUrl);
		postRequest.addHeader("content-type", "application/json");
		postRequest.setEntity(new StringEntity(bdMessageActionJSONObject.toJSONString(), Charset.defaultCharset()));

		HttpResponse response = httpRestClient.execute(postRequest);

		if (response.getStatusLine().getStatusCode() == 200) {
			System.out.println("Message Action with conditions was added successfully");
			InputStream inputStream = response.getEntity().getContent();
			byte[] bytes            = readStream(inputStream);
			String resultString     = new String(bytes); //json result
			JSONObject jsonResult   = (JSONObject)  parser.parse(resultString);
			System.out.println(jsonResult);
		} else {
			InputStream inputStream = response.getEntity().getContent();
			byte[] bytes            = readStream(inputStream);
			String resultString     = new String(bytes); //json error result
			System.out.println(resultString);
		}			
	}

	private static String getJsonMessageActionWithConditions() {
		String action =
		       "{" +
		       "\"security\": {" +
		            "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
		             "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
		       "}," +
		       "\"content\": {" +
		           "\"zone\": {" +
		               "\"zoneId\":" + "\"" + bdZoneId + "\"," +
		               "\"actions\": {" +
		                   "\"messageActions\": [" +
		                       "{" +
		                           "\"name\" : \"Date Range My message actions1\"," +
		                           "\"title\" : \"This is the title of my message.1\"," +
		                           "\"message\" : \"Have a nice day.1\"," +
		                           "\"conditions\": {" +
		                               "\"dateRange\": [" +
		                                   "{" +
		                                       "\"start\": \"10/11/2016\"," +
		                                       "\"end\": \"26/12/2017\"" +
		                                   "}" +
		                               "]," +
		                               "\"percentageCrossed\": [" +
		                                  "{" +
		                                      "\"percentage\": 90," +
		                                      "\"timeoutPeriod\": \"00:15\"," +
		                                      "\"sequential\": true" +
		                                   "}" +
		                              "]," +
		                              "\"timeActive\": [{" +
		                                "\"from\": {" +
		                                    "\"time\": \"06:01\"," +
		                                    "\"period\": \"am\" " +
		                                "}," +
		                                "\"to\": {" +
		                                    "\"time\": \"11:00\"," +
		                                    "\"period\": \"pm\" " +
		                                "}" +
		                            "}]," +
		                            "\"bearing\": [" +
		                                "{" +
		                                    "\"fromAngle\": 0," +
		                                    "\"toAngle\": 90" +
		                                "}" +
		                            "]," +
		                            "\"speed\": [" +
		                                "{" +
		                                    "\"minmumSpeed\": 10," +
		                                    "\"maximumSpeed\": 20" +
		                                "}" +
		                            "]" +
		                           "}" +
		                       "}" +
		                   "]" +
		               "}" +
		           "}" +
		       "}" +
		   "}";
		return action;
	}
}
