package com.bluedotinnovation.action;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.Charset;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;

import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import com.bluedotinnovation.common.BDCommon;

/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Add URL Action with Conditions client demonstrates adding an URL action with all conditions to an existing zone 
 * using JSON simple and Apache HTTP client libraries.
 */

public class AddURLActionWithConditions extends BDCommon {
	 private static String bdCustomerApiKey    = "a6598740-75f5-11e4-86ca-a0481cdc3311"; //This key is generated by Bluedot Point Access UI when your account is created.
     private static String bdApplicationApiKey = "5a9b1b78-3dd7-4f4d-8608-82408f3baf4c"; //This apiKey is generated when you create an application
     private static String bdZoneId            = "b80e50eb-b9f9-4ed5-966e-4b2e39cc0549"; //This is the id of the zone being updated. This can be fetched by calling GET Zones API
     private static String bdRestUrl           = "https://api.bluedotinnovation.com/1/actions";

     
 	public static void main(String[] args) throws IOException, ParseException, KeyManagementException, NoSuchAlgorithmException {		
 		CloseableHttpClient httpRestClient = HttpClients.custom().setSSLSocketFactory(getSSLContextFactory()).build();
 		
 		JSONParser parser    = new JSONParser();
 		JSONObject bdUrlActionJSONObject = (JSONObject) parser.parse(getJsonURLActionWithConditions()); //URL action with conditions json

 		HttpPost postRequest = new HttpPost(bdRestUrl);
 		postRequest.addHeader("content-type", "application/json");
 		postRequest.setEntity(new StringEntity(bdUrlActionJSONObject.toJSONString(), Charset.defaultCharset()));

 		HttpResponse response = httpRestClient.execute(postRequest);

 		if (response.getStatusLine().getStatusCode() == 200) {
 			System.out.println("URL Action with conditions was added successfully");
 			InputStream inputStream = response.getEntity().getContent();
 			byte[] bytes            = readStream(inputStream);
 			String resultString     = new String(bytes); //json result
 			JSONObject jsonResult   = (JSONObject)  parser.parse(resultString);
 			System.out.println(jsonResult);
 		} else {
 			InputStream inputStream = response.getEntity().getContent();
 			byte[] bytes            = readStream(inputStream);
 			String resultString     = new String(bytes); //json error result
 			System.out.println(resultString);
 		}			
 	}

    private static String getJsonURLActionWithConditions() {
    	
        String urlActionWithCondtionsJson =
             "{" +
                "\"security\": {" +
                    "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                    "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                "}," +
                "\"content\": {" +
                    "\"zone\": {" +
                        "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                        "\"actions\": {" +
                        "\"urlActions\": [" +
                            "{" +
                             "\"name\": \"Bluedot URL\"," +
                             "\"url\": \"http://www.bluedotinnovation.com\"" +
                                "\"conditions\": {" +
                                    "\"percentageCrossed\":" +
                                        "[" +
                                            "{" +
                                                "\"percentage\": 50," +
                                                "\"timeoutPeriod\": \"00:05\"" +
                                            "}" +
                                        "]," +
                                    "\"dateRange\": [" +
                                        "{" +
                                            "\"start\": \"01/03/2014\"," +
                                            "\"end\": \"14/12/2014\"" +
                                        "}" +
                                    "]," +
                                    "\"timeActive\": [{" +
                                        "\"from\": {" +
                                            "\"time\": \"06:01\"," +
                                            "\"period\": \"am\" " +
                                        "}," +
                                        "\"to\": {" +
                                            "\"time\": \"11:00\"," +
                                            "\"period\": \"pm\" " +
                                        "}" +
                                    "}]" +
                                "}" +
                            "}" +
                        "]" +
                      "}" +
                    "}" +
                "}" +
            "}";
        return urlActionWithCondtionsJson;
    }
}
