package com.bluedotinnovation.action;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.Charset;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;

import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.conn.ssl.SSLSocketFactory;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.impl.client.HttpClients;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import com.bluedotinnovation.common.BDCommon;

/**
 * @author
 *
 */

public class UpdateURLAction extends BDCommon
{
	private static String bdCustomerApiKey    = "ca4c8d11-6942-11e4-ba4b-a0481cdc3311"; //This key is generated by Bluedot Access UI when you register
	private static String bdApplicationApiKey = "f5223f4c-a0f3-47be-ba59-080b6290a9d4"; //This apiKey is generated when you create an application
    private static String bdRestUrl           = "https://api.bluedotinnovation.com/1/actions";
	private static String bdZoneId            = "dfafb7fd-d2f7-42ec-afd5-d5c7851c0396"; //This is the id of the zone being updated. This can be fetched by calling zones/getAll API
	private static String actionId            = "ead2b62c-83c0-486a-973b-596396cc292e"; //This is the id of the action being updated. This can be fetch by calling zones/get?id=yourzoneid
	
	public static void main(String[] args) throws ParseException, IOException, KeyManagementException, NoSuchAlgorithmException
	{
		CloseableHttpClient httpRestClient = HttpClients.custom().setSSLSocketFactory(new SSLSocketFactory(getSSLContext())).build();
		
		HttpPost postRequest = new HttpPost(bdRestUrl);
  
	    JSONParser parser    = new JSONParser();
	    JSONObject bdUrlActionJSONObject = (JSONObject) parser.parse(getJsonUrlAction()); //URL action json
				    		    
		postRequest.addHeader("content-type", "application/json");

		postRequest.setEntity(new StringEntity(bdUrlActionJSONObject.toJSONString(), Charset.defaultCharset()));
	 
	    HttpResponse response = httpRestClient.execute(postRequest);
	    	    	    
        if (response.getStatusLine().getStatusCode() == 200)
        {
        	System.out.println("URL action was updated successfully");
        	InputStream inputStream = response.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json result
        	JSONObject jsonResult   = (JSONObject)  parser.parse(resultString);
        	System.out.println(jsonResult);
        }
        else 
        {
        	InputStream inputStream = response.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json error result
        	System.out.println(resultString);
        }	
	}
    
	private static String getJsonUrlAction()
    {
    		String urlActionJson =
    			 "{" +
    	            "\"security\": {" +
    	                "\"apiKey\":" + "\"" + bdApplicationApiKey +"\"," +
    	                "\"customerApiKey\":" +"\"" + bdCustomerApiKey + "\""+
    	            "}," +
    	            "\"content\": {" +
    	                "\"zone\": {" +
    	                    "\"zoneId\":"+ "\"" + bdZoneId +"\"," +
    	                    "\"actions\": {" +
    	                        "\"urlActions\": [" +
    	                            "{" +
    	                                "\"actionId\":"+ "\"" + actionId +"\"," +
    	                                "\"name\": \"Bluedot URL Updated\"," +
    	                                "\"url\": \"http://www.bluedotinnovation.commmm\"" +
    	                            "}" +
    	                        "]" +
    	                    "}" +
    	                "}" +
    	            "}" +
    	        "}";		
    	return urlActionJson;
    }
  
}
