package com.bluedotinnovation.checkin;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;

import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import com.bluedotinnovation.common.BDCommon;

/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * CheckInActivity client demonstrates fetching checkIn activities for a given zone.
 * 100 CheckIn activities are returned per call, increment the page number parameter to get records corresponding to the page
 * This api also accepts a date range as parameter(optional) where records within the start date and the end date range are returned
 */

public class BDCheckinActivityClient extends BDCommon {
	
    private static String bdCustomerApiKey    = "b2a9e860-2890-11e6-8148-0639e7649356"; //This key is generated by Bluedot Point Access UI when your account is created.
    private static String bdApplicationApiKey = "14163ef0-2891-11e6-8148-0639e7649356"; //This apiKey is generated when you create an application
    private static String bdZoneId            = "c6814aba-d582-4b9e-8788-924f1a0a4c8a"; //This is the id of the zone being updated. This can be fetched by calling This can be fetched by calling GET Zones API API
    private static String receivedAtStart     = "2016-06-05";
    private static String receivedAtEnd       = "2016-06-07";
    private static String checkInTimeStart    = "2016-09-13";
    private static String checkInTimeEnd      = "2016-09-05";    
    private static String bdRestBaseUrl       = "https://api.bluedotinnovation.com/2/checkinactivities";

	public static void main(String[] args) throws IOException, ParseException, KeyManagementException, NoSuchAlgorithmException {
		
		//getAllCheckInActivitesByApplication();
		getAllCheckInActivitesByZone();
		//getCheckInActivitiesByReceivedAtDateRange();
		//getCheckInActivitiesByCheckInTimeDateRange
		
	}
	
	public static void getAllCheckInActivitesByApplication() throws IOException, ParseException, KeyManagementException, NoSuchAlgorithmException {
    	
    	String bdRestUrl = bdRestBaseUrl + "?&customerApiKey=" + bdCustomerApiKey + "&apiKey=" + bdApplicationApiKey + "&pageNumber=0";
    	
    	CloseableHttpClient httpRestClient = HttpClients.custom().setSSLSocketFactory(getSSLContextFactory()).build();
		HttpGet request            = new HttpGet(bdRestUrl);
		HttpResponse httpResponse  = httpRestClient.execute(request);
		
		if (httpResponse.getStatusLine().getStatusCode() == 200) {
			BufferedReader rd          = new BufferedReader (new InputStreamReader
					                    (httpResponse.getEntity().getContent()));
			JSONParser parser          = new JSONParser();
			String bdChecInRecords;
			
			while ((bdChecInRecords = rd.readLine()) != null) {
			     Object object                = parser.parse(bdChecInRecords);
			     JSONArray bdCheckInJsonArry  = (JSONArray) object;

			     for (Object checkInObject : bdCheckInJsonArry) {
			    	 JSONObject jsonObject = (JSONObject) checkInObject;
			    	 
				     /*Print checkIn records returned*/			     
			    	 System.out.println("Check-in ID : " + jsonObject.get("checkInId").toString());
				     System.out.println("Check-in Time : " +  jsonObject.get("CheckInTime"));
				     System.out.println("Zone ID :  " + jsonObject.get("zoneId"));
				     System.out.println("Zone Name :  " + jsonObject.get("zoneName"));
				     System.out.println("Device Speed : " + jsonObject.get("deviceSpeed"));
				     System.out.println("Device Type : " + jsonObject.get("deviceType"));
				     System.out.println("Installation Ref : " + jsonObject.get("installRef")); // This is a fully randomised id and the real application id or device id is never stored in the db
				     System.out.println("---------\n");
				}		    
			}
		} else {
			InputStream inputStream = httpResponse.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json error result
        	System.out.println(resultString);
		}
    }

	public static void getAllCheckInActivitesByZone() throws IOException, ParseException, KeyManagementException, NoSuchAlgorithmException {
    	
    	String bdRestUrl = bdRestBaseUrl + "?&customerApiKey=" + bdCustomerApiKey + "&apiKey=" + bdApplicationApiKey + "&zoneId=" + bdZoneId + "&pageNumber=0";
    	
    	CloseableHttpClient httpRestClient = HttpClients.custom().setSSLSocketFactory(getSSLContextFactory()).build();
		HttpGet request            = new HttpGet(bdRestUrl);
		HttpResponse httpResponse  = httpRestClient.execute(request);
		
		if (httpResponse.getStatusLine().getStatusCode() == 200) {
			BufferedReader rd          = new BufferedReader (new InputStreamReader
					                    (httpResponse.getEntity().getContent()));
			JSONParser parser          = new JSONParser();
			String bdChecInRecords;
			
			while ((bdChecInRecords = rd.readLine()) != null) {
			     Object object                = parser.parse(bdChecInRecords);
			     JSONArray bdCheckInJsonArry  = (JSONArray) object;

			     for (Object checkInObject : bdCheckInJsonArry) {
			    	 JSONObject jsonObject = (JSONObject) checkInObject;
			    	 
				     /*Print checkIn records returned*/			     
			    	 System.out.println("Check-in ID : " + jsonObject.get("checkInId").toString());
				     System.out.println("Check-in Time : " +  jsonObject.get("CheckInTime"));
				     System.out.println("Zone ID :  " + jsonObject.get("zoneId"));
				     System.out.println("Zone Name :  " + jsonObject.get("zoneName"));
				     System.out.println("Device Speed : " + jsonObject.get("deviceSpeed"));
				     System.out.println("Device Type : " + jsonObject.get("deviceType"));
				     System.out.println("Installation Ref : " + jsonObject.get("installRef")); // This is a fully randomised id and the real application id or device id is never stored in the db
				     System.out.println("---------\n");
				}		    
			}
		} else {
			InputStream inputStream = httpResponse.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json error result
        	System.out.println(resultString);
		}
    }
	
	public static void getCheckInActivitiesByReceivedAtDateRange() throws IOException, ParseException, KeyManagementException, NoSuchAlgorithmException {
    	
		String bdRestUrl = bdRestBaseUrl + "?&customerApiKey=" + bdCustomerApiKey + "&apiKey=" + bdApplicationApiKey + 
				"&receivedAtStart=" + receivedAtStart + "&receivedAtEnd=" + receivedAtEnd + "&pageNumber=0";
		
		CloseableHttpClient httpRestClient = HttpClients.custom().setSSLSocketFactory(getSSLContextFactory()).build();
		HttpGet request            = new HttpGet(bdRestUrl);
		HttpResponse httpResponse  = httpRestClient.execute(request);
		
		if (httpResponse.getStatusLine().getStatusCode() == 200){
			BufferedReader rd          = new BufferedReader (new InputStreamReader
					                    (httpResponse.getEntity().getContent()));
			JSONParser parser          = new JSONParser();
			String bdChecInRecords;
			
			while ( (bdChecInRecords = rd.readLine() ) != null) {
			     Object object                = parser.parse(bdChecInRecords);
			     JSONArray bdCheckInJsonArry  = (JSONArray) object;
			     
			     for (Object checkInObject : bdCheckInJsonArry) {
			    	 
			    	 JSONObject jsonObject        = (JSONObject) checkInObject;
			    	 
				     /*Print checkIn records returned*/			     
				     System.out.println("Check-in ID : " + jsonObject.get("checkInId").toString());
				     System.out.println("Check-in Time : " +  jsonObject.get("CheckInTime"));
				     System.out.println("Zone ID :  " + jsonObject.get("zoneId"));
				     System.out.println("Zone Name :  " + jsonObject.get("zoneName"));
				     System.out.println("Device Speed : " + jsonObject.get("deviceSpeed"));
				     System.out.println("Device Type : " + jsonObject.get("deviceType"));
				     System.out.println("Installation Ref : " + jsonObject.get("installRef")); // This is a fully randomised id and the real application id or device id is never stored in the db
				     System.out.println("---------\n");
				}
			    
			}
		} else {
			InputStream inputStream = httpResponse.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json error result
        	System.out.println(resultString);
		}
    }
	
    
    
    public static void getCheckInActivitiesByCheckInTimeDateRange() throws IOException, ParseException, KeyManagementException, NoSuchAlgorithmException {
    	
		String bdRestUrl = bdRestBaseUrl + "?&customerApiKey=" + bdCustomerApiKey + "&apiKey=" + bdApplicationApiKey + 
				"&checkInTimeStart=" + checkInTimeStart + "&checkInTimeEnd=" + checkInTimeEnd + "&pageNumber=0";
		
		CloseableHttpClient httpRestClient = HttpClients.custom().setSSLSocketFactory(getSSLContextFactory()).build();
		HttpGet request            = new HttpGet(bdRestUrl);
		HttpResponse httpResponse  = httpRestClient.execute(request);
		
		if (httpResponse.getStatusLine().getStatusCode() == 200){
			BufferedReader rd          = new BufferedReader (new InputStreamReader
					                    (httpResponse.getEntity().getContent()));
			JSONParser parser          = new JSONParser();
			String bdChecInRecords;
			
			while ( (bdChecInRecords = rd.readLine() ) != null) {
			     Object object                = parser.parse(bdChecInRecords);
			     JSONArray bdCheckInJsonArry  = (JSONArray) object;
			     
			     for (Object checkInObject : bdCheckInJsonArry) {
			    	 
			    	 JSONObject jsonObject        = (JSONObject) checkInObject;
			    	 
				     /*Print checkIn records returned*/			     
				     System.out.println("Check-in ID : " + jsonObject.get("checkInId").toString());
				     System.out.println("Check-in Time : " +  jsonObject.get("CheckInTime"));
				     System.out.println("Zone ID :  " + jsonObject.get("zoneId"));
				     System.out.println("Zone Name :  " + jsonObject.get("zoneName"));
				     System.out.println("Device Speed : " + jsonObject.get("deviceSpeed"));
				     System.out.println("Device Type : " + jsonObject.get("deviceType"));
				     System.out.println("Installation Ref : " + jsonObject.get("installRef")); // This is a fully randomised id and the real application id or device id is never stored in the db
				     System.out.println("---------\n");
				}
			    
			}
		} else {
			InputStream inputStream = httpResponse.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json error result
        	System.out.println(resultString);
		}
    }
}
