package com.bluedotinnovation.beacon;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;

import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import com.bluedotinnovation.common.BDCommon;

/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Get All Beacons client demonstrates listing all the beacons added to the customer's account from Bluedot backend 
 * using Apache HTTP client and JSON Simple libraries.
 */
public class GetAllBeacons extends BDCommon {

	public static void main(String[] args) throws IOException, KeyManagementException, NoSuchAlgorithmException, ParseException {
		
		String bdCustomerApiKey 	= "7cd1ea80-d40e-11e4-84cb-b8ca3a6b879d"; //This key is generated by Bluedot Point Access UI when your account is created.
		String bdRestUrl            = "https://api.bluedotinnovation.com/1/beacons?customerApiKey=" + bdCustomerApiKey;

		CloseableHttpClient httpRestClient = HttpClients.custom().setSSLSocketFactory(getSSLContextFactory()).build();
		HttpGet request       = new HttpGet(bdRestUrl);
		HttpResponse response = httpRestClient.execute(request);
		BufferedReader rd     = new BufferedReader (new InputStreamReader(response.getEntity().getContent()));
		JSONParser parser          = new JSONParser();
		String bdApplicationJSON = "";
		while ((bdApplicationJSON = rd.readLine()) != null) {
			Object object = parser.parse(bdApplicationJSON);
			JSONArray bdApplicationJsonArray = (JSONArray) object;
			for (Object applicationObject : bdApplicationJsonArray){
			    JSONObject jsonObject =  (JSONObject) applicationObject;
			    System.out.println("Beacon name : " + jsonObject.get("name"));
			    System.out.println("Beacon ID: " + jsonObject.get("beaconId"));
			    System.out.println("Latitude: " + jsonObject.get("latitude"));
			    System.out.println("Longitude: " + jsonObject.get("longitude"));
			    System.out.println("Description: " + jsonObject.get("description"));
			    System.out.println("---------\n");
			}
		}
	}
}
