package com.bluedotinnovation.beacon;

import com.bluedotinnovation.common.BDCommon;

import org.apache.http.HttpResponse;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import java.io.IOException;
import java.io.InputStream;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;

/**
 * @author Bluedot Innovation
 * Update Beacon java client demonstrates adding a beacon to your Bluedot backend using Apache HTTP client and JSON Simple libraries.
 */
public class UpdateBeacon extends BDCommon {
	
	private static String bdCustomerApiKey    = "86577370-7b91-11e4-bcb7-a0481cdc3311"; //This key is generated by Bluedot Access UI when you register
	private static String bdApplicationApiKey = "13a9d8e0-b255-11e4-a423-00155d53317c"; //This apiKey is generated when you create an application
	private static String bdBeaconId          = "ad1a5c15-d3c7-4903-a067-d1cd5d11be1b"; //This is the id of the beacon being updated.
	private static String bdRestUrl           = "https://api.bluedotinnovation.com/1/beacons";

	/**
	 * @param args
	 * @throws IOException 
	 * @throws ClientProtocolException 
	 * @throws ParseException 
	 * @throws NoSuchAlgorithmException 
	 * @throws KeyManagementException 
	 */
	public static void main(String[] args) throws ClientProtocolException, IOException, ParseException, KeyManagementException, NoSuchAlgorithmException {
		
		CloseableHttpClient httpRestClient = HttpClients.custom().setSSLSocketFactory(getSSLContextFactory()).build();
		
		JSONParser parser    = new JSONParser();
		JSONObject bdUpdateBeaconJSONObject = (JSONObject) parser.parse(getJsonUpdateBeacon()); //update the beacon value
		
		HttpPost postRequest = new HttpPost(bdRestUrl);
		postRequest.addHeader("content-type", "application/json");
		postRequest.setEntity(new StringEntity(bdUpdateBeaconJSONObject.toJSONString()));
		
		HttpResponse response = httpRestClient.execute(postRequest);
		
		if (response.getStatusLine().getStatusCode() == 200) {
        	System.out.println("Beacon was successfully created");
        	InputStream inputStream = response.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json result
        	JSONObject jsonResult   = (JSONObject)  parser.parse(resultString);
        	System.out.println(jsonResult);
        } else {
        	InputStream inputStream = response.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json error result
        	System.out.println(resultString);
        }	
	}
	
	private static String getJsonUpdateBeacon() {
		
		String updateBeaconJson =  
				"{" +
		           "\"security\": {" +
		            "\"apiKey\":"+ "\"" + bdApplicationApiKey +"\","+
		            "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\" "+
		        "}," + 
		        "\"content\": {" +
		            "\"beacon\": {" +
		               "\"beaconId\":" + "\"" + bdBeaconId +"\"," +
		               "\"name\": \"Bluedot building\"," +
					   "\"proximityUUID\": \"f7826da6-4fa2-4e98-8024-bc4b71e0894e\"," +
					   "\"longitude\": \"123.34455\"," +
					   "\"latitude\": \"47.777888\"," +
					   "\"type\":  \"Both\"," +
					   "\"major\": 12," +
					   "\"minor\": 13," +
					   "\"macAddress\": \"01:17:C5:31:84:21\"," +
					   "\"txPower\": -77," +
					   "\"description\": \"Sample description\"" +
		            "}"+
		        "}"+
		     "}";
		return updateBeaconJson;
	}
		
}
