package com.bluedotinnovation.zone;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.Charset;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;
import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import com.bluedotinnovation.common.BDCommon;

/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Add Complete Zone client demonstrates adding a complete zone which has fences, beacons and actions
 * to an existing application using Apache HTTP client and JSON Simple libraries.
 */

public class AddCompleteZone extends BDCommon {
	
	private static String bdCustomerApiKey    = "86577370-7b91-11e4-bcb7-a0481cdc3311"; //This key is generated by Bluedot Point Access UI when your account is created.
	private static String bdApplicationApiKey = "9beebb18-ec2e-4f30-8e1c-2286c77007d4"; //This apiKey is generated when you create an application
    private static String bdRestUrl       = "https://api.bluedotinnovation.com/1/zones";

	public static void main(String[] args) throws ParseException, IOException, KeyManagementException, NoSuchAlgorithmException {
		
		CloseableHttpClient httpRestClient = HttpClients.custom().setSSLSocketFactory(getSSLContextFactory()).build();
		
	    JSONParser parser    = new JSONParser();
	    JSONObject bdZoneJSONObject = (JSONObject) parser.parse(getJsonCompleteZoneActiveAllDay()); //JSON of zone which is active during 06:00 AM - 11:00 PM

		HttpPost postRequest = new HttpPost(bdRestUrl);
		postRequest.addHeader("content-type", "application/json");
		postRequest.setEntity(new StringEntity(bdZoneJSONObject.toJSONString(), Charset.defaultCharset()));
	 
	    HttpResponse response = httpRestClient.execute(postRequest);
	    	    	    
        if (response.getStatusLine().getStatusCode() == 200) {
        	System.out.println("Zone was added successfully");
        	InputStream inputStream = response.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json result
        	JSONObject jsonResult   = (JSONObject)  parser.parse(resultString);
        	System.out.println(jsonResult);
        } else {
        	InputStream inputStream = response.getEntity().getContent();
        	byte[] bytes            = readStream(inputStream);
        	String resultString     = new String(bytes); //json error result
        	System.out.println(resultString);
        }			

	}

	/*Return JSON for a complete Zone with a beacon and a custom action which is active for a certain time period during the day. 
	 * Time values have a format of HH:MM and the period value has to be one of {am/pm}*/
    private static String getJsonCompleteZoneTimeActive() {
        return "{" +
	         "\"security\": {" +
                "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
	        "}," +
	       "\"content\": {" +
	             "\"zone\": {" +
	                "\"zoneName\": \"First Test Bluedot Zone\"," +
	                "\"minimumRetriggerTime\": \"11:11\"," +
	                "\"enableCheckOut\": true," +
	                "\"timeActive\" : {" +
	                    "\"from\": {" +
	                        "\"time\": \"06:00\"," +
	                        "\"period\": \"am\"" +
	                    "}," +
	                    "\"to\": {" +
	                        "\"time\": \"11:00\"," +
	                        "\"period\": \"pm\"" +
	                    "}" +
	                "}," +
	                "\"actions\": {" +
	                    "\"customActions\": [" +
	                        "{" +
	                            "\"name\": \"A Custom Application action\"" +
	                        "}" +
	                    "]" +
	                "}," +
	                "\"beacons\": [" +
		            	"{" +
			               "\"beaconId\":  \"b22ea927-f757-4a8f-8ba7-2960a4b688b2\"," +
			    		   "\"proximity\": 1," +
			    		   "\"order\": 1" +
			    		"}"+
			    	"]"+
	            "}" +
	        "}" +
	    "}";
    }
    
    /*Return JSON for a complete Zone which is active all day with a circular geofence and a message action.*/
	private static String getJsonCompleteZoneActiveAllDay() {
		return "{" +
	        "\"security\": {" +
		           "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
		           "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
	       "}," +
	       "\"content\": {" +
	           "\"zone\": {" +
	               "\"zoneName\": \"First Test Bluedot Zone-Updated\"," +
	               "\"minimumRetriggerTime\": \"11:11\"," +
	               "\"enableCheckOut\": true," +
	               "\"activeAllDay\": true," +
	               "\"fences\": {" +
	                   "\"circles\": [" +
	                       "{"+
	                           "\"name\": \"Circle-1\","+
	                           "\"color\": \"#000ffff\","+
	                           "\"radius\": \"30.330384237225\","+
	                           "\"center\": {"+
	                               "\"latitude\": -37.818780,"+
	                               "\"longitude\": 144.980734 "+
	                           "},"+
	                           "\"order\": 2" +
	                       "}" +
	                   "]" +
	               "},"+
	               "\"actions\": {" +
	                   "\"messageActions\": [" +
	                       "{" +
	                           "\"name\": \"Welcome to MCG\"," +
	                           "\"title\": \"MCG Welcome Message\"," +
	                           "\"message\": \"Welcome to MCG\"" +
	                       "}" +
	                   "]" +
	               "}" +
	           "}" +
	       "}" +
	   "}";
	}
}